### ISSUE TITLE
Error when file doesn't exists

### ISSUE THREAD

**Issue by JaviRpo** [StephanThierry/ftp-delete-action#10]
I'm running the action and want to delete the file but it sometimes could not exist.

This is the error
```
rm: Access failed: 550 Could not delete www/config.json: No such file or directory
```

It would be great if the plugin doesn't fail or an option to omit the error and continue.

**Comment by StephanThierry** [comment]
The rm command is called with the -f option that should solve this... what version of the action are you running?

**Comment by JaviRpo** [comment]
This is my definition

```
- name: Delete previous elements
      uses: StephanThierry/ftp-delete-action@v1
      with:
        host: ${{ secrets.ftp_server }}
        user: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        remoteFiles: "certificate/cert.pfx;certificate/cert.key"
        workingDir: "/www"
        ignoreSSL: "1"
```
